version: '2'
services:
    examt-app:
        image: examt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://examt-mysql:3306/examt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    examt-mysql:
        extends:
            file: mysql.yml
            service: examt-mysql
